package com.tsukimiai.hoshi.ai.cognition;

public enum AiCognitionTaskType {
    EMOTION_CLASSIFICATION,
    SESSION_TITLE,
    SESSION_COMPACTION,
    MEMORY_EXTRACTION,
    MEMORY_RECONCILIATION,
    PROACTIVE_OPENING,
    PROACTIVE_TIMING_JUDGMENT,
    PROACTIVE_FOLLOW_UP_JUDGMENT,
    PROACTIVE_FOLLOW_UP_CONTENT
}
